version: '3.2'

networks:
  App:


services:
  db:
    image: postgres:12.12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: peem2544
      POSTGRES_DB: expenses
    restart: on-failure
    networks:
      - App
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s #The time between each health check execution
      timeout: 10s #The maximum time allowed for a single health check execution
      retries: 5
    ports:
      - "5432:5432"

  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   container_name: expenses-gin
  #   env_file:
  #     - ./env/server.env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   networks:
  #     - App
  #   ports:
  #     - "2565:2565"
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: user@domain.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_LISTEN_PORT: 80
  #     PGADMIN_DEFAULT_SERVER: db
  #     PGADMIN_DEFAULT_SERVER_PORT: 5432
  #     PGADMIN_DEFAULT_SERVER_DB: PostgresDemo
  #     PGADMIN_DISABLE_RUNTIME_CONFIG: 1
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - App
